#!/bin/zsh
# set PATH so it includes user's private bin if it exists

setopt extendedglob

zstyle ':completion:*' completer _complete _ignored _expand_alias
autoload -Uz compinit
compinit


# deactivate xon/xoff in order to allof ctrl-s and ctrl-q command to vim and tmux
stty -ixon

alias python=python3

alias ll='ls -alF'
alias la='ls -A'
alias l='ls -CF'

alias fif='ag -S -f ' # find in file, searches hidden but not in git dir and follow symlinks
alias fij='fif --java ' # find in java file, searches for content in java files only
alias fip='fif --php ' # find in php files, searches for content in php files only
alias fijs='fif --js ' # searches in javascript files, search for content in javascript files only
alias ff='fif -g ' # find file, search for the pattern in file path and print the files names only, content is not searched
alias fp='ps aux | grep ' # find a process
alias swd='ddg' # search the web with duck duck go for the search given search string, opens the result in the default browser
alias swg='google' # search the web with google for the given search string, opens the result in the default browser.

alias acs='apt search'
alias agi='sudo apt-get install'

alias vi='gvim -v'
alias vim='gvim -v'

alias dc=docker-compose

alias gs='git status'
alias gd='git diff'
alias gdc='git diff --cached'
alias gpu='git push'
alias gpl='git pull'
alias gpuu='git push -u origin `git rev-parse --abbrev-ref HEAD`'

alias op='gio open'
alias dirsync='rsync -avh --info=progress2 --delete '
#uses the system and x-window clipboard to create a diff view between the content of the two clipboards
alias clipdiff='vimdiff <(xclip -o) <(xclip -o -selection clipbord)'

alias kc='kubectl' 

alias -g ...='../..'
alias -g ....='../../..'

#alias finjar='find "$1" -name "*.jar" -exec sh -c \'unzip -l {}|grep -H --label {} \'$2\'\' \;'
# open man pages using vim with the vman command and setting the filetype to manpages.
vm() { vim -c 'setf man' <(man $1); }
# vm has the same auto completion as man
compdef vm=man

EDITOR=/usr/bin/vim
KUBECONFIG="${KUBECONFIG:-$HOME/.kube/config}"
GOPATH=~/hack/go
GOBIN=~/hack/go/bin
JAVA_HOME=~/.sdkman/candidates/java/current

PATH="$PATH:$JAVA_HOME/bin:$HOME/.dotfiles/bin:$HOME/.local/bin:$HOME/.npm-global/bin:$HOME/projects/wescale/bin:$GOPATH/bin"

export PATH TERM EDITOR KUBECONFIG GOPATH GOBIN JAVA_HOME

# see https://youtrack.jetbrains.com/issue/IDEA-78860 for more info
export IBUS_ENABLE_SYNC_MODE=1

###-begin-yo-completion-###
_yo_completion () {
  local cword line point words si
  read -Ac words
  read -cn cword
  let cword-=1
  read -l line
  read -ln point
  si="$IFS"
  IFS=$'\n' reply=($(COMP_CWORD="$cword" \
    COMP_LINE="$line" \
    COMP_POINT="$point" \
    yo-complete completion -- "${words[@]}" \
    2>/dev/null)) || return $?
  IFS="$si"
}
compctl -K _yo_completion yo
###-end-yo-completion-###
##

function currentKubeContext {
    echo `kubectl config current-context`;
}
# RPROMPT='$(currentKubeContext)'


# merge the gnome gtk clipboard with the x11 clipboard.
#autocutsel &
#autocutsel -s PRIMARY & 
