#!/bin/zsh
# set PATH so it includes user's private bin if it exists

# deactivate xon/xoff inorder to allof ctrl-s and ctrl-q commandt to vim and tmux
stty -ixon

alias ll='ls -alF'
alias la='ls -A'
alias l='ls -CF'
alias ff='ag -ilu --hidden . -g $1 '
alias fin='ag -iua --hidden $1'

#alias finjar='find "$1" -name "*.jar" -exec sh -c \'unzip -l {}|grep -H --label {} \'$2\'\' \;'
# open man pages using vim with the vman command and setting the filetype to manpages.
vman() { vim -c 'setf man' <(man $1); }

CXX=/usr/bin/g++
CC=/usr/bin/gcc
ARDUINO_SDK_PATH=~/local/arduino
AVR="$ARDUINO_SDK_PATH/hardware/tools/avr"

GRAILS_HOME=~/hack/grails
JAVA_HOME=/opt/Oracle_Java/jdk
GWT_HOME=~/hack/gwt
MAVEN_HOME=/usr/share/maven
M2_HOME=/usr/share/maven
ANDROID_SDK_HOME=~/local/android-sdk
ANDROID_SDK=~/local/android-sdk
GRADLE_HOME=~/local/gradle

PATH="$PATH:$GRAILS_HOME/bin:$JAVA_HOME/bin:$ANDROID_SDK_HOME/platform-tools:$AVR/bin:$GRADLE_HOME/bin:~/.dotfiles/bin"

export GRAILS_HOME PATH JAVA_HOME MAVEN_HOME M2_HOME ANDROID_SDK_HOME CC CXX ARDUINO_SDK_PATH AVR GRADLE_HOME TERM ANDROID_SDK

# see https://youtrack.jetbrains.com/issue/IDEA-78860 for more info
export IBUS_ENABLE_SYNC_MODE=1
