#!/bin/bash
# set PATH so it includes user's private bin if it exists

TERM=xterm-256color
# deactivate xon/xoff inorder to allof ctrl-s and ctrl-q commandt to vim and tmux
stty -ixon

# use "vman manpage" to open manpage with vim.
# taken from https://github.com/jez/vim-superman
vman() {
  vim -c "SuperMan $*"

  if [ "$?" != "0" ]; then
    echo "No manual entry for $*"
  fi
}
complete -o default -o nospace -F _man vman

alias ll='ls -alF'
alias la='ls -A'
alias l='ls -CF'
alias ff='ag -il . -g $1 '
alias fin='ag -i $1'
#alias finjar='find "$1" -name "*.jar" -exec sh -c \'unzip -l {}|grep -H --label {} \'$2\'\' \;'
alias iedit='~/local/idea/bin/idea.sh $1'
alias idiff='~/local/idea/bin/idea.sh diff $1 $2'
alias inspect='~/local/idea/bin/inspect.sh -v1 $1'

CXX=/usr/bin/g++
CC=/usr/bin/gcc

ARDUINO_SDK_PATH=~/local/arduino
AVR="$ARDUINO_SDK_PATH/hardware/tools/avr"

GRAILS_HOME=~/hack/grails
JAVA_HOME=/opt/Oracle_Java/jdk
GWT_HOME=~/hack/gwt
MAVEN_HOME=/usr/share/maven
M2_HOME=/usr/share/maven
ANDROID_SDK_HOME=~/local/android-sdk-linux
GRADLE_HOME=~/local/gradle
PATH="$PATH:$GRAILS_HOME/bin:$JAVA_HOME/bin:$ANDROID_SDK_HOME/platform-tools:$AVR/bin:$GRADLE_HOME/bin:~/.dotfiles/bin"

export GRAILS_HOME PATH JAVA_HOME MAVEN_HOME M2_HOME ANDROID_SDK_HOME CC CXX ARDUINO_SDK_PATH AVR GRADLE_HOME TERM

# see https://youtrack.jetbrains.com/issue/IDEA-78860 for more info
export IBUS_ENABLE_SYNC_MODE=1
